---
title: "NYC_COVID_Data_Exploration"
author: "Rahul Subramanian"
date: "4/26/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load Libraries

```{r load_lib}
rm(list = ls())
library(plyr)
library(tidyverse)
library(magrittr)
library(tibble)
library(stringi)
library(pomp)
library(xtable)
source("load_libraries_essential.R")
#library(panelPomp)
#library(foreach)
#library(iterators)
#library(doRNG)
#library(aakmisc) ## available at https://kingaa.github.io/
stopifnot(packageVersion("pomp")>="2.2")
#stopifnot(packageVersion("panelPomp")>="0.9.1")
#stopifnot(packageVersion("aakmisc")>="0.26.2")
options(
  stringsAsFactors=FALSE,
  keep.source=TRUE,
  encoding="UTF-8"
)
set.seed(407958184)
source("rahul_theme.R")
```

## Load Raw Data
```{r}
boros_raw = read.csv(file = "../Down_Data/boro.csv")
head(boros_raw)
by_age_raw = read.csv(file = "../Down_Data/by-age.csv")
head(by_age_raw)
by_sex_raw = read.csv(file = "../Down_Data/by-sex.csv")
head(by_sex_raw)
case_hosp_death_raw = read.csv(file = "../Down_Data/case-hosp-death.csv")
head(case_hosp_death_raw)


summary_raw = read.csv(file = "../Down_Data/summary.csv")
head(summary_raw)
tests_by_zcta_raw = read.csv(file = "../Down_Data/tests-by-zcta.csv")
head(tests_by_zcta_raw)
nrow(tests_by_zcta_raw)

testing_raw = read.csv(file = "../Down_Data/testing.csv")
head(testing_raw)


```
Note: The file testing.csv was not on the current version of the NYC
 git repo, but an older commit:
 
 https://github.com/nychealth/coronavirus-data/blob/6968ca6f4a23c04f9a51ec2e3b161c41cd437bdb/testing.csv


 Download link: https://raw.githubusercontent.com/nychealth/coronavirus-data/6968ca6f4a23c04f9a51ec2e3b161c41cd437bdb/testing.csv

### Read in NY State Testing Raw Data
```{r}
NY_state_raw_testing_data = read.csv("../Down_Data/New_York_State_Statewide_COVID-19_Testing.csv")
head(NY_state_raw_testing_data)
```



```{r}





date_of_NY_testing_rec = as.Date("03/20/2020", "%m/%d/%Y")
date_of_NY_testing_rec_with_delay = date_of_NY_testing_rec + days(2)
one_week_after_testing_rec = date_of_NY_testing_rec_with_delay + weeks(1)


```

## PCR Positive Rate analysis
### NY State testing Data
```{r}
head(NY_state_raw_testing_data)
NYC_county_list = c("Brooklyn", "Kings", "Queens", "Bronx", "Richmond",
                    "New York")
NYC_Counties_full_testing_data = NY_state_raw_testing_data %>%
  filter(County %in% NYC_county_list)
NYC_Counties_full_testing_data

NYC_full_testing_data = NYC_Counties_full_testing_data %>%
  group_by(Test.Date) %>%
  summarize(New_Positives = sum(New.Positives),
            Cumulative_Number_of_Positives =
              sum(Cumulative.Number.of.Positives),
            Total_Number_of_Tests_Performed = 
              sum(Total.Number.of.Tests.Performed),
            Cumulative_Number_of_Tests_Performed =
              sum(Cumulative.Number.of.Tests.Performed)) %>%
  as.data.frame()

head(NYC_full_testing_data)
NYC_full_testing_data = NYC_full_testing_data %>%
  mutate(Prop_Pos = New_Positives/Total_Number_of_Tests_Performed)
NYC_full_testing_data = NYC_full_testing_data %>%
  mutate(Not_Pos = Total_Number_of_Tests_Performed - New_Positives,
         Date = as.Date(Test.Date, "%m/%d/%Y"))

p = ggplot(data = NYC_full_testing_data,
           aes(x = Date, y = Prop_Pos)) + geom_point() +
  rahul_theme
p

p = ggplot(data = NYC_full_testing_data,
           aes(x = Date, y = Not_Pos)) + geom_point() +
  rahul_theme
p

p = ggplot(data = NYC_full_testing_data,
           aes(x = Date, y = log(Not_Pos))) + geom_point() +
  rahul_theme
p

write.csv(NYC_full_testing_data,
          file = "../Generated_Data/NYC_full_testing_data.csv",
          row.names = FALSE)

```

